workflows: Disable doctests
Github workflows currently failing with ghc-9.2

     Preprocessing library 'hackport-internal' for hackport-0.8.5.1...
     doctest: Missing file: /usr/local/.ghcup/ghc/9.2.8/lib/ghc-9.2.8/settings
     Error: [Cabal-7125]

Signed-off-by: hololeap <hololeap@protonmail.com>