Fix autogen-modules errors from `cabal check`
Add Paths_hackport to autogen-modules in the stanzas for the hackport
executable and the doctests test-suite.

Update cabal submodule to 481674183. Remove references to pregenerated
Paths_* modules. (Reverts commit 9fc0b25eba8679fd7ab9db4a5a80283a65e7dabf.)

Use Distribution.Client.Version to get cabal-install's version.

Hopefully this will keep `cabal check` from getting confused:

    Error: [no-autogen-paths] Packages using 'cabal-version: 2.0' and
    the autogenerated module Paths_* must include it also on the
    'autogen-modules' field besides 'exposed-modules' and
    'other-modules'.

Signed-off-by: hololeap <hololeap@protonmail.com>